# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestingEx' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

    pod 'Moya'
    pod 'Moya/RxSwift'
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'ObjectMapper'
    pod 'Moya-ObjectMapper/RxSwift'
    pod 'SwiftyJSON'
    pod 'SVProgressHUD'

  target 'TestingExTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestingExUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
