# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestingEx' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

    # Pods for API service using Moya
    pod 'Moya'
    pod 'Moya/RxSwift'
    pod 'Moya-ObjectMapper'
    pod 'Moya-ObjectMapper/RxSwift'
    pod 'ObjectMapperAdditions/Core'
    # rx
    pod 'RxSwift', '~> 4.0'
    pod 'RxCocoa', '~> 4.0'
    # progress hud
    pod 'SVProgressHUD'
    # image rendering and caching
    pod 'Kingfisher'
    # Swinject
    pod 'Swinject', '2.5.0'
    pod 'SwinjectAutoregistration', '2.5.0'
    pod 'SwinjectStoryboard', :git => 'https://github.com/Swinject/SwinjectStoryboard.git', :tag => '2.1.0'
    # List
    pod 'IGListKit'
    # JSON
    pod 'SwiftyJSON'

  target 'TestingExTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestingExUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
