# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MVVM_Swinject_Rx' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MVVM_Swinject_Rx
  pod 'Moya'
  pod 'Moya/RxSwift'
  pod 'Moya-ObjectMapper'
  pod 'Moya-ObjectMapper/RxSwift'
  pod 'ObjectMapperAdditions/Core'
  pod 'RxCocoa'
  
  pod 'IGListKit'
  pod 'Kingfisher'
  
  pod 'Swinject', '2.5.0'
  pod 'SwinjectAutoregistration', '2.5.0'
  pod 'SwinjectStoryboard', :git => 'https://github.com/Swinject/SwinjectStoryboard.git', :tag => '2.1.0'

end
